### ISSUE TITLE
aliases are not persistent

### ISSUE THREAD

**Issue by gibbling** [oh-my-fish/plugin-balias#2]
Not sure if this is how this plugin was supposed to function but creating an alias works and is usable in the window it was made but open a new terminal and the alias is not present.  I can use funcsave and the alias name to apparently make them persistent.  Is this plugin supposed to save these aliases or is it possibly something that might be possible to have as an option with a --save flag or something?

**Comment by bpinto** [comment]
If you want to create a permanent alias, you have to add it to one of the files that are automatically loaded.

E.g. Any `.load` file in the custom folder.
`~/.oh-my-fish/custom/aliases.load`

```
balias apti 'sudo apt-get install'
```

Or to the end of the `~/.config/fish/config.fish` file.

**Comment by gibbling** [comment]
Thanks for the clarification.
