### ISSUE TITLE
balias not found

### ISSUE THREAD

**Issue by jney** [oh-my-fish/plugin-balias#3]
just trying to install balias, but it can't be found :

```
➜  ~ omf install balias
Trying to clone from URL...
fatal: repository 'balias' does not exist
Could not install package balias.
```

**Comment by bobthecow** [comment]
Sorry, balias hasn't been updated to the new omf architecture yet, so it can't be installed like that. You can see the list of plugins which have been updated here:

https://github.com/oh-my-fish/oh-my-fish/tree/master/db/pkg

You might be able to install in manually via the URL, e.g.: 

```
omf install https://github.com/oh-my-fish/plugin-balias.git
```

… and it _might_ work as-is. But it hasn't been updated and confirmed yet so your mileage may vary. Alternatively, you could try it, take a shot at updating it and open a pull request :)

**Comment by daveyarwood** [comment]
> You might be able to install in manually via the URL, e.g.:
> 
> ```
> omf install https://github.com/oh-my-fish/plugin-balias.git
> ```

This worked for me :+1:

**Comment by FabioAntunes** [comment]
This issue can be closed, since today I tried `omf install balias` and it's working
